Fix syntax error in Lighthouse workflow

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -26,12 +26,8 @@ jobs:
         run: npm install -g @lhci/cli
 
       - name: Run Lighthouse CI
-        run: lhci autorun || echo "Lighthouse finished with some errors"
-
-      - name: Debug: Locate Lighthouse report
         run: |
-          echo "Поиск report.html:"
-          find . -name "report.html"
+          lhci autorun || echo "Lighthouse finished with some errors"
 
       - name: Upload report
         uses: actions/upload-artifact@v4
